### ISSUE TITLE
Keyspaces?

### ISSUE THREAD

**Issue by danlentz** [MyPost/cassius#1]
Forgive the question if it is something I'm misunderstanding or overlooking.  Is it possible to work with individual keyspaces rather than database-at-a-time semantics?  Ie, rather than drop-in clearing the whole database, just one keyspace while leaving the others unaffected?

**Comment by pokle** [comment]
Yes you can work with individual keyspaces. For example, here's how you use drop-in to drop just a single keyspace:

```
(drop-in db ["my-keyspace"])
```

The other functions work in a similar way:

```
(peek-in db ["my-keyspace"]) ; peeks the whole keyspace
(peek-in db ["my-keyspace" "my-table"]) ; peeks just my-table in my-keyspace
```

Cheers!
